analyzer:
  exclude:
    - "lib/generated/l10n.dart"
    - "lib/generated/intl/messages_all.dart"
    - "lib/generated/intl/messages_en.dart"

linter:
  rules:
    always_use_package_imports: true
    prefer_single_quotes: true
    avoid_print: true
    eol_at_end_of_file: true
    prefer_final_locals: true
    prefer_const_constructors: false
