name: Dart

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Note: This workflow uses the latest stable version of the Flutter SDK.
      # You can specify other versions if desired:
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze --fatal-infos
      
      - name: Build app
        run: flutter build

      - name: Run tests
        run: flutter test
